[package]
name = "readyset-server"
version = "0.7.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

readme = "README.md"
description = "The ReadySet data-flow database server"

keywords = ["database", "dataflow", "backend", "storage", "sql"]
categories = ["database", "database-implementations"]

[features]
default = []
generate_mysql_tests = ["default"]
profiling = ["timekeeper/default"]
bench = ["dataflow/bench"]
failure_injection = ["fail/failpoints", "readyset-client/failure_injection", "dataflow/failure_injection", "replicators/failure_injection"]
# Redact the display of strings marked sensitive from logs and error messages
redact_sensitive = ["readyset-util/redact_sensitive"]

[target.'cfg(not(target_env="msvc"))'.dependencies]
tikv-jemallocator = "0.4"

[dependencies]
clap = { version = "3.0", features = ["derive","env"] }
anyhow = "1.0"
thiserror = "1.0.26"
ahash = "0.7"
futures = "0.3"
futures-core = "0.3.14"
futures-util = "0.3.14"
futures-sink = "0.3.14"
futures-executor = "0.3.14"
pin-project = "1.0"
hyper = { version = "0.14.10", features = [ "stream", "server" ] }
querystring = "1.1.0"
itertools = "0.10"
metrics = "0.19"
metrics-util = "0.13"
metrics-exporter-prometheus = "0.10"
nom = "7.1"
petgraph = { version = "0.5", features = ["serde-1"] }
rand = "0.7.0"
serde_json = "1.0.2"
serde_with = "1.9.4"
slab = "0.4"
bincode = "1.3.3"
tokio = { workspace = true, features = ["full"] }
async-bincode = "0.6.1"
tracing = { version = "0.1", features = ["release_max_level_debug"] }
stream-cancel = "0.8.0"
vec1 = "1.6.0"
reqwest = "0.11.3"
url = { version = "2.2", features = ["serde"] }
tokio-stream = "0.1.5"
lazy_static = "1.4.0"
regex = "1.5.4"
tracing-futures = "0.2.5"
parking_lot = "0.11.2"
tikv-jemalloc-ctl = "0.4"
scopeguard = "1.1.0"
fail = "0.5.0"
sha1 = "0.10"
derive_more = "0.99"
streaming-iterator = "0.1"
proptest = "1.0.0"
once_cell = "1.14"

timekeeper = { version = "0.3.2", default-features = false }
vec_map = { version = "0.8.0", features = ["eders"] }
serde = { version = "1.0.8", features = ["rc", "derive"] }
zookeeper = "0.6"
tokio-tower = "0.5.1"
tower = { version = "0.4.6", features = ["util"] }
strawpoll = "0.2.2"

# local deps
dataflow = { path = "../readyset-dataflow", package = "readyset-dataflow" }
mir = { path = "../readyset-mir", package = "readyset-mir" }
common = { path = "../readyset-common", package = "readyset-common" }
readyset-client = { path = "../readyset-client" }
failpoint-macros = { path = "../failpoint-macros" }
readyset-errors = { path = "../readyset-errors" }
readyset-data = { path = "../readyset-data" }
readyset-util = { path = "../readyset-util" }
replicators = { path = "../replicators" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
array2 = { path = "../array2" }
nom-sql = { path = "../nom-sql" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter" }
readyset-version = { path = "../readyset-version" }
health-reporter = { path = "../health-reporter" }
database-utils = { path = "../database-utils" }

[dev-dependencies]
test-utils = { path = "../test-utils" }
backtrace = { version = "0.3.2", features = ["serialize-serde"] }
toml = "0.5"
diff = "0.1.10"
tempfile = "3.2"
mysql = "22.0.0"
chrono = "0.4.19"
serial_test = "0.5.1"
assert_approx_eq = "1.1.0"
assert_unordered = "0.3"
criterion = "0.3"
include_dir = "0.6.2"
rusty-fork = "0.3.0"
test-strategy = "0.2.0"
rust_decimal = "1.25"
triomphe = "0.1"

[[bench]]
name = "dataflow"
harness = false
