dist: trusty
language: rust
rust:
  - nightly
cache: cargo
env:
  - SETTLE_TIME=2000
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - cargo install rustfmt-nightly --vers 0.2.9 --force
script:
  - cargo fmt -- --write-mode=diff
  - cargo test --verbose
