dist: trusty
language: rust
rust:
  - nightly
cache: cargo
env:
  - SETTLE_TIME=2000
script:
  - cargo check --all --all-targets
  - cargo test --verbose --all
addons:
  apt:
    packages:
    - libhwloc-dev
