dist: trusty
language: rust
rust:
  - nightly-2018-09-28
env:
  - SETTLE_TIME=2000
script:
  - cargo check --all --all-targets
  - cargo test --verbose --all -- --test-threads=1
addons:
  apt:
    packages:
    - liblz4-dev
