variables:
  nightly: 2019-07-19

stages:
 - stage: check
   displayName: Compilation check
   dependsOn: []
   jobs:
     - template: azure/cargo-check.yml@templates
       parameters:
         name: cargo_check
         rust: nightly-$(nightly)
         benches: true
 - stage: test
   dependsOn: check
   jobs:
    - job: test
      displayName: "cargo test"
      strategy:
        matrix:
          Linux:
            vmImage: ubuntu-16.04
          MacOS:
            vmImage: macOS-10.14
      pool:
        vmImage: $(vmImage)
      steps:
       - template: azure/install-rust.yml@templates
         parameters:
           rust: nightly-$(nightly)
       - script: cargo test --all -- --test-threads=1
         displayName: Run tests
         env:
          SETTLE_TIME: 2000
 - stage: style
   displayName: Style linting
   dependsOn: check
   jobs:
     - template: azure/rustfmt.yml@templates
       parameters:
         name: rustfmt
         rust: nightly-$(nightly)

resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      endpoint: mit-pdos
