[workspace]
members = [
    "msql-srv",
    "nom-sql",
    "noria-client",
    "noria-mysql",
    "noria-psql",
    "noria/noria",
    "noria/server",
    "noria/applications",
    "noria/tools",
    "noria/noria-logictest",
    "noria/timestamp_service",
    "psql-srv",
    "unbounded-interval-tree",
    "launchpad",
    "connectors/debezium_connector",
    "query_generator"
]
[profile.release]
debug=true
