[workspace]
members = [
	"noria",
	"noria-server",
	"noria-benchmarks",
	"noria-benchmarks/lobsters",
]

[profile.release]
debug=true

[patch.crates-io]
tower-balance = { git = "https://github.com/tower-rs/tower.git" }
tower-load = { git = "https://github.com/tower-rs/tower.git" }
tokio-tower = { git = "https://github.com/tower-rs/tokio-tower.git" }
trawler = { git = "https://github.com/jonhoo/trawler.git", branch = "revamp" }
