[patch.crates-io]
tokio-postgres = { git = "https://github.com/readysettech/rust-postgres.git" }
mysql_async = { git = "https://github.com/readysettech/mysql_async", branch = "lru-fix" }
eui48 = { git = "https://github.com/readysettech/eui48.git", branch = "master" }

[workspace]
members = [
    "database-utils",
    "mysql-srv",
    "mysql-time",
    "nom-sql",
    "noria-client",
    "noria-client/test-helpers",
    "noria-mysql",
    "noria-psql",
    "noria/data",
    "noria/errors",
    "noria/noria",
    "noria/server",
    "noria/server/sql-passes",
    "noria/server/dataflow/partial_map",
    "noria/server/dataflow/reader_map",
    "noria/server/dataflow/state",
    "noria/applications",
    "noria/clustertest",
    "noria/clustertest/macros",
    "failpoint-macros",
    "failpoint-macros/proc-macros",
    "noria/tools",
    "noria/noria-logictest",
    "noria/timestamp_service",
    "psql-srv",
    "merging-interval-tree",
    "launchpad",
    "replicators",
    "query_generator",
    "maths",
    "metrics-aggregator",
    "test_utils",
    "readyset-tracing",
    "readyset-tracing/proc-macros",
    "readyset-repl",
]
resolver = "2"

[profile.release]
debug=true
