[package]
name = "distributary"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[features]
web = ["rustful", "rustc-serialize"]

[dependencies]
petgraph = "0.2"
shortcut = "3.3"
clocked-dispatch = "3.0"
parking_lot = {version = "0.2", features = ["nightly"]}

docopt = "0.6"
rand = "0.3"
randomkit = "0.1.0"

postgres = "0.11"
r2d2 = "0.7"
r2d2_postgres = "0.10"
time = "0.1"

memcache = {git="https://github.com/aisk/rust-memcache.git"}

# for web
rustful = { version = "0.9", optional = true }
rustc-serialize = { version = "0.3", optional = true }

tarpc = "0.6"
serde = "0.8"
serde_macros = "0.8"

[profile.release]
debug=true

[lib]
name = "distributary"
path = "src/lib.rs"

[[bin]]
name = "web"
path = "src/web/main.rs"

[[bin]]
name = "bench_votes"
path = "benchmarks/votes.rs"

[[bin]]
name = "gen_voter"
path = "benchmarks/gen_voter.rs"
