[package]
name = "distributary"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[features]
web = ["rustful"]
b_memcached = ["memcached-rs"]
b_mysql = ["mysql"]
b_mssql = ["futures", "futures-state-stream", "tiberius", "tokio-core"]
b_netsoup = ["bincode", "net2", "bufstream"]
b_hybrid = ["mysql", "memcached-rs"]
default = ["web", "b_netsoup", "b_memcached", "b_mysql", "b_mssql", "b_hybrid"]
profiling = ["timekeeper/default"]
binaries = ["default"]
generate_mysql_tests = ["default"]

[dependencies]
chrono = { version = "0.3.0", features = ["serde"] }
itertools = "0.6.0"
petgraph = "0.4.4"
regex = "0.2.1"
fnv = "1.0.3"
serde = { version = "1.0.2", features = ["rc"] }
serde_derive = "1.0.2"
slog = "2.0.2"
#slog = { version = "2.0.2", features = ["max_level_trace", "release_max_level_debug"] }
slog-term = "2.0.0"

evmap = "0.6.4"
arccstr = "0.4.0"
vec_map = "0.8.0"
lazy_static = "0.2.8"

nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "1b79ea9978fd1a348fb6dcac72bfa6bdad34711d" }

# for benchmarks
# cli
clap = "2.24.0"
# distributions
rand = "0.3"
zipf = "0.2.0"
# sampling
hdrsample = "4.0.0"
# mssql
futures-state-stream = { version = "0.1", optional = true }
tiberius = { git = "https://github.com/ms705/tiberius/", optional = true }
# mysql
mysql = { version = "11.0.0", optional = true }
# memcached
memcached-rs = { git = "https://github.com/jonhoo/memcached-rs.git", branch = "expose-multi", optional = true }
# netsoup
bincode = { version = "0.8.0", optional = true }
net2 = { version = "0.2.29", optional = true }
bufstream = { version = "0.1", optional = true }
# futures
futures = { version ="0.1.9", optional = true }
tokio-core = { version = "0.1.6", optional = true }

# durable log
snowflake = "1.2.0"
serde_json = "1.0.1"
buf_redux = "0.6.1"
time = "0.1"

[dev-dependencies]
toml = "0.4.0"

[dependencies.rustful]
version = "0.9.0"
default-features = false
features = ["rustc_json_body", "multipart"]
optional = true

[dependencies.timekeeper]
version = "0.2.4"
default-features = false
# for Mac OS X build
# git = "https://github.com/ms705/timekeeper"

[profile.dev]
codegen-units = 1

[profile.test]
codegen-units = 1

[profile.release]
debug=true

[lib]
name = "distributary"
path = "src/lib.rs"

[[example]]
name = "basic-recipe"
required-features = ["binaries"]

[[bin]]
name = "web"
path = "src/web/main.rs"
required-features = ["binaries"]

[[bin]]
name = "web_sql"
path = "src/web/sql_main.rs"
required-features = ["binaries"]

[[bin]]
name = "bank"
path = "benchmarks/bank/bank.rs"
required-features = ["binaries"]

[[bin]]
name = "vote"
path = "benchmarks/vote/vote.rs"
required-features = ["binaries"]

[[bin]]
name = "vote-server"
path = "benchmarks/vote/vote-server.rs"
required-features = ["binaries"]

[[bin]]
name = "vote-client"
path = "benchmarks/vote/vote-client.rs"
required-features = ["binaries"]

[[bin]]
name = "tpc_w"
path = "benchmarks/tpc_w/tpc_w.rs"
required-features = ["binaries"]

[[bin]]
name = "hotsoup"
path = "benchmarks/hotsoup/hotsoup.rs"
required-features = ["binaries"]

[[bin]]
name = "extract_hotcrp_queries"
path = "benchmarks/hotsoup/extract_queries.rs"
required-features = ["binaries"]

[[bin]]
name = "piazza"
path = "benchmarks/piazza/piazza.rs"
required-features = ["binaries"]

[[bin]]
name = "vote-new-fraction"
path = "benchmarks/vote/vote-new-fraction.rs"
required-features = ["binaries"]
