[workspace]
members = [
	"noria",
	"noria-server",
	"noria-benchmarks",
	"noria-benchmarks/lobsters",
]

[profile.release]
debug=true

[patch.crates-io]
tokio-tower = { git = "https://github.com/tower-rs/tokio-tower.git", branch = "no-box" }
