[workspace]
members = [
	"noria",
	"noria-server",
	"noria-benchmarks",
	"noria-benchmarks/lobsters",
]

[profile.release]
debug=true

[patch.crates-io]
# https://github.com/tower-rs/tokio-tower/pull/6
tokio-tower = { git = "https://github.com/tower-rs/tokio-tower.git", branch = "no-box" }
# https://github.com/tokio-rs/tokio/pull/2160
tokio = { git = "https://github.com/tokio-rs/tokio.git", branch = "jonhoo/preempt" }
# https://github.com/rust-lang/futures-rs/pull/2049#issuecomment-579022335
futures-util = { git = "https://github.com/rust-lang/futures-rs.git" }
futures-core = { git = "https://github.com/rust-lang/futures-rs.git" }
futures-sink = { git = "https://github.com/rust-lang/futures-rs.git" }
# https://github.com/bonifaido/rust-zookeeper/pull/66
zookeeper = { git = "https://github.com/jonhoo/rust-zookeeper.git", branch = "bump-more-deps" }
# https://github.com/crossbeam-rs/crossbeam/pull/460#issuecomment-573145406
crossbeam-epoch = { git = "https://github.com/crossbeam-rs/crossbeam.git" }
crossbeam-utils = { git = "https://github.com/crossbeam-rs/crossbeam.git" }
# https://github.com/slog-rs/term/pull/28#issuecomment-579352146
slog-term = { git = "https://github.com/slog-rs/term.git" }
# https://github.com/zonyitoo/memcached-rs/pull/13
memcached-rs = { git = "https://github.com/jonhoo/memcached-rs.git", branch = "bump-deps" }
# https://github.com/Detegr/rust-ctrlc/pull/64
ctrlc = { git = "https://github.com/kornelski/rust-ctrlc.git", branch = "nix" }
# https://github.com/sfackler/rust-openssl/pull/1219
openssl-sys = { git = "https://github.com/sfackler/rust-openssl.git" }
