[patch.crates-io]
tokio-postgres = { git = "https://github.com/readysettech/rust-postgres.git" }
mysql_async = { git = "https://github.com/readysettech/mysql_async", branch = "lru-fix" }
eui48 = { git = "https://github.com/readysettech/eui48.git", branch = "master" }

[workspace]
members = [
    "array2",
    "database-utils",
    "dataflow-expression",
    "dataflow-state",
    "failpoint-macros",
    "failpoint-macros/proc-macros",
    "launchpad",
    "maths",
    "merging-interval-tree",
    "metrics-aggregator",
    "mysql-srv",
    "mysql-time",
    "nom-sql",
    "partial-map",
    "psql-srv",
    "query-generator",
    "reader-map",
    "readyset",
    "readyset-client",
    "readyset-client-adapter",
    "readyset-client-metrics",
    "readyset-client-test-helpers",
    "readyset-clustertest",
    "readyset-common",
    "readyset-clustertest",
    "readyset-data",
    "readyset-dataflow",
    "readyset-errors",
    "readyset-logictest",
    "readyset-mir",
    "readyset-mysql",
    "readyset-psql",
    "readyset-repl",
    "readyset-server",
    "readyset-sql-passes",
    "readyset-tools",
    "readyset-tracing",
    "readyset-tracing/proc-macros",
    "replicators",
    "test-utils",
    "timestamp-service",
    "tournament-kway"
]
resolver = "2"

[profile.release]
debug=true
