[patch.crates-io]
tokio-postgres = { git = "https://github.com/readysettech/rust-postgres.git" }
mysql_async = { git = "https://github.com/readysettech/mysql_async", branch = "lru-fix" }
eui48 = { git = "https://github.com/readysettech/eui48.git", branch = "master" }

[workspace]
members = [
    "array2",
    "benchmarks",
    "concrete-iter",
    "database-utils",
    "dataflow-expression",
    "dataflow-state",
    "failpoint-macros",
    "failpoint-macros/proc-macros",
    "launchpad",
    "merging-interval-tree",
    "metrics-aggregator",
    "mysql-srv",
    "mysql-time",
    "nom-sql",
    "partial-map",
    "psql-srv",
    "query-generator",
    "reader-map",
    "readyset",
    "readyset-adapter",
    "readyset-client",
    "readyset-client-metrics",
    "readyset-client-test-helpers",
    "readyset-clustertest",
    "readyset-common",
    "readyset-clustertest",
    "readyset-data",
    "readyset-dataflow",
    "readyset-errors",
    "readyset-logictest",
    "readyset-mir",
    "readyset-mysql",
    "readyset-psql",
    "readyset-repl",
    "readyset-server",
    "readyset-sql-passes",
    "readyset-telemetry-reporter",
    "readyset-tools",
    "readyset-tracing",
    "readyset-tracing/proc-macros",
    "readyset-version",
    "replicators",
    "system-benchmarks",
    "test-utils",
    "timestamp-service",
    "tournament-kway",
    "health-reporter"
]
resolver = "2"

[workspace.dependencies]
consulrs = { git = "https://github.com/readysettech/consulrs.git", branch = "allow-disabling-rustls-tls-2" }
eui48 = { git = "https://github.com/readysettech/eui48.git", branch = "master", default-features = false }
mysql_async = { git = "https://github.com/readysettech/mysql_async", branch = "lru-fix" }
nperf-core = { git = "https://github.com/readysettech/not-perf.git" }
postgres = { git = "https://github.com/readysettech/rust-postgres.git" }
postgres-native-tls = { git = "https://github.com/readysettech/rust-postgres.git" }
postgres-protocol = { git = "https://github.com/readysettech/rust-postgres.git" }
postgres-types = { git = "https://github.com/readysettech/rust-postgres.git" }
tokio-postgres = { git = "https://github.com/readysettech/rust-postgres.git" }

[profile.release]
debug=true
