[package]
name = "distributary"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[features]
web = ["rustful", "rustc-serialize"]
b_memcached = ["memcached-rs"]
b_postgresql = ["postgres"]
b_mysql = ["mysql"]
b_mssql = ["futures", "futures-state-stream", "tiberius", "tokio-core"]
b_netsoup = ["futures", "tokio-core", "tarpc", "tarpc-plugins", "serde", "serde_derive"]
b_hybrid = ["mysql", "memcached-rs"]
default = ["web", "b_netsoup", "b_memcached", "b_mysql", "b_mssql", "b_hybrid"]
profiling = ["timekeeper/default"]
binaries = ["default"]

[dependencies]
chrono = "0.3.0"
itertools = "0.5"
petgraph = "0.4"
regex = "0.1"
fnv = "1.0"
slog = "1.5.2"
#slog = { version = "1.5.2", features = ["max_level_trace", "release_max_level_debug"] }
slog-term = "1.5.0"

evmap = "0.2.0"
arccstr = "0.3.2"

spmc = "0.2.1"
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "7fbdbc4093bb10d345cfe579a4b7280dfc342ac9" }

# for benchmarks
# cli
clap = "2.13"
# distributions
rand = "0.3"
# sampling
hdrsample = "2.1"
# postgresql
postgres = { version = "0.11", optional = true }
# mssql
futures-state-stream = { version = "0.1", optional = true }
tiberius = { git = "https://github.com/ms705/tiberius/", optional = true }
# mysql
mysql = { version = "10.0", optional = true }
# memcached
memcached-rs = { version = "0.1.2", optional = true }
# netsoup
futures = { version ="0.1.9", optional = true }
tokio-core = { version = "0.1", optional = true }
tarpc = {git="https://github.com/google/tarpc.git", optional = true}
tarpc-plugins = { git = "https://github.com/google/tarpc", optional = true }
serde = { version = "0.9", optional = true }
serde_derive = { version = "0.9", optional = true }

# for web
rustc-serialize = { version = "0.3", optional = true }

[dependencies.rustful]
version = "0.9"
default-features = false
features = ["rustc_json_body", "multipart"]
optional = true

[dependencies.timekeeper]
version = "0.2.4"
default-features = false
# for Mac OS X build
# git = "https://github.com/ms705/timekeeper"

[profile.release]
debug=true

[lib]
name = "distributary"
path = "src/lib.rs"

[[example]]
name = "basic-recipe"
required-features = ["binaries"]

[[bin]]
name = "web"
path = "src/web/main.rs"
required-features = ["binaries"]

[[bin]]
name = "web_sql"
path = "src/web/sql_main.rs"
required-features = ["binaries"]

[[bin]]
name = "bank"
path = "benchmarks/bank/bank.rs"
required-features = ["binaries"]

[[bin]]
name = "vote"
path = "benchmarks/vote/vote.rs"
required-features = ["binaries"]

[[bin]]
name = "vote-server"
path = "benchmarks/vote/vote-server.rs"
required-features = ["binaries"]

[[bin]]
name = "vote-client"
path = "benchmarks/vote/vote-client.rs"
required-features = ["binaries"]

[[bin]]
name = "multitail"
path = "benchmarks/multitail/multitail.rs"
required-features = ["binaries"]

[[bin]]
name = "tpc_w"
path = "benchmarks/tpc_w/tpc_w.rs"
required-features = ["binaries"]

[[bin]]
name = "hotsoup"
path = "benchmarks/hotsoup/hotsoup.rs"
required-features = ["binaries"]

[[bin]]
name = "extract_hotcrp_queries"
path = "benchmarks/hotsoup/extract_queries.rs"
required-features = ["binaries"]

[[bin]]
name = "piazza"
path = "benchmarks/piazza/piazza.rs"
required-features = ["binaries"]
