[package]
name = "distributary"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[workspace]
members = ["benchmarks", "channel", "daemon"]

[features]
web = ["rustful"]
default = ["web"]
profiling = ["timekeeper/default"]
binaries = ["default"]
generate_mysql_tests = ["default"]

[dependencies]
backtrace = { version = "0.3.2", features = ["serialize-serde"] }
bincode = { version = "0.8.0" }
bufstream = { version = "0.1.3" }
chrono = { version = "0.4.0", features = ["serde"] }
itertools = "0.6.0"
petgraph = { git = "https://github.com/fintelia/petgraph", branch = "serde", features = ["serde"] }
regex = "0.2.2"
fnv = "1.0.5"
# tarpc
tokio-core = { version = "0.1.8" }
# memcached hooks
memcached-rs = { git = "https://github.com/jonhoo/memcached-rs.git", branch = "expose-multi" }
# mysql output comparison tests
mysql = { version = "11.2.0" }
serde = { version = "1.0.8", features = ["rc"] }
serde_derive = "1.0.8"
slog = "2.0.6"
#slog = { version = "2.0.6", features = ["max_level_trace", "release_max_level_debug"] }
slog-term = "2.0.1"
mio = "0.6.9"
tarpc = "0.9.0"
tarpc-plugins = "0.2.0"

bus = "1.3.0"
evmap = "1.0.0"
arccstr = "1.0.2"
vec_map = { version = "0.8.0", features = ["eders"] }
hurdles = "1.0.0"
arrayvec = "0.4.0"

nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "7758136babe72f470b7ea9fea384fca4f47db647"}

# durable log
snowflake = "1.3.0"
serde_json = "1.0.2"
buf_redux = "0.6.1"

channel = { path = "channel" }

# Not needed directly, but we want to force the version used by our dependencies to have default
# features. If this isn't here, then the features used for `num` will vary between subcrates,
# triggering unnecessary recompiles.
num = "0.1"

[dev-dependencies]
toml = "0.4.1"
backtrace = { version = "0.3.2", features = ["serialize-serde"] }
diff = "0.1.10"

[dependencies.rustful]
version = "0.9.0"
default-features = false
features = ["rustc_json_body", "multipart"]
optional = true

[dependencies.timekeeper]
version = "0.2.4"
default-features = false
# for Mac OS X build
# git = "https://github.com/ms705/timekeeper"

[profile.dev]
codegen-units = 1

[profile.test]
codegen-units = 1

[profile.release]
debug=true

[lib]
name = "distributary"
path = "src/lib.rs"

[[example]]
name = "basic-recipe"

[[bin]]
name = "web"
path = "src/web/main.rs"
required-features = ["binaries"]

[[bin]]
name = "web_sql"
path = "src/web/sql_main.rs"
required-features = ["binaries"]
