[package]
name = "distributary"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[workspace]
members = ["benchmarks", "channel", "daemon"]

[features]
web = ["rustful"]
default = ["web"]
profiling = ["timekeeper/default"]
binaries = ["default"]
generate_mysql_tests = ["default"]

[dependencies]
serde_derive = "1.0.8"
serde_json = "1.0.2"
bufstream = "0.1.3"
itertools = "0.6.0"
buf_redux = "0.6.1"
bincode = "0.9.0"
mysql = "11.2.0"
regex = "0.2.2"
fnv = "1.0.5"
mio = "0.6.9"
bus = "1.3.0"
#slog = { version = "2.0.6", features = ["max_level_trace", "release_max_level_debug"] }
slog = "2.0.6"
tarpc = "0.9.0"
evmap = "1.0.0"
arccstr = "1.0.2"
hurdles = "1.0.0"
arrayvec = "0.4.0"
snowflake = "1.3.0"
slog-term = "2.0.1"
tokio-core = "0.1.8"
tarpc-plugins = "0.2.0"

# need features
backtrace = { version = "0.3.2", features = ["serialize-serde"] }
vec_map = { version = "0.8.0", features = ["eders"] }
chrono = { version = "0.4.0", features = ["serde"] }
serde = { version = "1.0.8", features = ["rc"] }

# git deps
petgraph = { git = "https://github.com/fintelia/petgraph", branch = "serde", features = ["serde"] }
memcached-rs = { git = "https://github.com/jonhoo/memcached-rs.git", branch = "expose-multi" }
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "b01998fc34a5d473387987110724a395298fc6c0"}

# local deps
channel = { path = "channel" }

# Not needed directly, but we want to force the version used by our
# dependencies to have default features. If this isn't here, then the features
# used for `num` will vary between subcrates, triggering unnecessary
# recompiles.
num = "0.1"

[dependencies.rustful]
version = "0.9.0"
default-features = false
features = ["rustc_json_body", "multipart"]
optional = true

[dependencies.timekeeper]
version = "0.2.4"
default-features = false
# for Mac OS X build
# git = "https://github.com/ms705/timekeeper"

[dev-dependencies]
backtrace = { version = "0.3.2", features = ["serialize-serde"] }
toml = "0.4.1"
diff = "0.1.10"

[profile.release]
debug=true

[lib]
name = "distributary"
path = "src/lib.rs"

[[example]]
name = "basic-recipe"

[[bin]]
name = "web"
path = "src/web/main.rs"
required-features = ["binaries"]

[[bin]]
name = "web_sql"
path = "src/web/sql_main.rs"
required-features = ["binaries"]
