[patch.crates-io]
tokio-postgres = { git = "https://github.com/readysettech/rust-postgres.git" }
bindgen = { git = "https://github.com/rust-lang/rust-bindgen.git", branch = "master" }
mysql_async = { git = "https://github.com/readysettech/mysql_async", branch = "lru-fix" }
mysql_common = { git = "https://github.com/readysettech/rust_mysql_common.git", branch = "zero-terminated-nonce" }
mysql = { git = "https://github.com/readysettech/rust-mysql-simple.git", branch = "lru-fix" }

[workspace]
members = [
    "msql-srv",
    "mysql-time",
    "nom-sql",
    "noria-client",
    "noria-client/test-helpers",
    "noria-mysql",
    "noria-psql",
    "noria/errors",
    "noria/noria",
    "noria/server",
    "noria/applications",
    "noria/clustertest",
    "noria/clustertest/macros",
    "failpoint-macros",
    "failpoint-macros/proc-macros",
    "noria/tools",
    "noria/noria-logictest",
    "noria/timestamp_service",
    "psql-srv",
    "unbounded-interval-tree",
    "launchpad",
    "replicators",
    "readyset-logging",
    "query_generator",
    "maths",
    "metrics-aggregator",
    "test_utils",
]
[profile.release]
debug=true
