[workspace]
members = [
	"noria",
	"noria-server",
	"noria-benchmarks",
	"noria-benchmarks/lobsters",
]

[profile.release]
debug=true

[patch.crates-io]
tower-service = { git = "https://github.com/jonhoo/tower.git", branch = "all" }
tower-direct-service = { git = "https://github.com/jonhoo/tower.git", branch = "all" }
tower-discover = { git = "https://github.com/jonhoo/tower.git", branch = "all"  }
tower-balance = { git = "https://github.com/jonhoo/tower.git", branch = "all"  }
tower-buffer = { git = "https://github.com/jonhoo/tower.git", branch = "all"  }
tower-util = { git = "https://github.com/jonhoo/tower.git", branch = "all"  }
