[patch.crates-io]
tokio-postgres = { git = "https://github.com/readysettech/rust-postgres.git" }
mysql = { git = "https://github.com/readysettech/rust-mysql-simple.git" }

[workspace]
members = [
    "msql-srv",
    "mysql-time",
    "nom-sql",
    "noria-client",
    "noria-mysql",
    "noria-psql",
    "noria/noria",
    "noria/server",
    "noria/applications",
    "noria/clustertest",
    "noria/tools",
    "noria/noria-logictest",
    "noria/timestamp_service",
    "psql-srv",
    "unbounded-interval-tree",
    "launchpad",
    "replicators",
    "readyset-logging",
    "query_generator",
    "maths",
]
[profile.release]
debug=true
