[workspace]
members = [
	"noria",
	"noria-server",
	"noria-benchmarks",
	"noria-benchmarks/lobsters",
]

[profile.release]
debug=true

[patch.crates-io]
# https://github.com/tower-rs/tokio-tower/pull/6
tokio-tower = { git = "https://github.com/tower-rs/tokio-tower.git", branch = "no-box" }
# https://github.com/tokio-rs/tokio/pull/2160
tokio = { git = "https://github.com/tokio-rs/tokio.git", branch = "jonhoo/preempt" }
# https://github.com/crossbeam-rs/crossbeam/pull/460#issuecomment-573145406
crossbeam-epoch = { git = "https://github.com/crossbeam-rs/crossbeam.git" }
crossbeam-utils = { git = "https://github.com/crossbeam-rs/crossbeam.git" }
# https://github.com/Detegr/rust-ctrlc/pull/64
ctrlc = { git = "https://github.com/kornelski/rust-ctrlc.git", branch = "nix" }
