[package]
name = "distributary"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[features]
web = ["rustful", "rustc-serialize"]

[dependencies]
petgraph = "0.2"
shortcut = "3.3"
clocked-dispatch = "3.0"
parking_lot = {version = "0.2", features = ["nightly"]}

docopt = "0.6"
rand = "0.3"
randomkit = "0.1.0"

# for web
rustful = { version = "0.9", optional = true }
rustc-serialize = { version = "0.3", optional = true }

[profile.release]
debug=true

[lib]
name = "distributary"
path = "src/lib.rs"

[[bin]]
name = "web"
path = "src/web/main.rs"

[[bin]]
name = "bench_votes"
path = "benchmarks/votes.rs"
