version: "3.8"
services:
  consul-server:
    image: consul
    restart: always
    volumes:
      - ./docker/consul/server.json:/consul/config/server.json:ro
    command: 'agent -bootstrap-expect=1'
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=noria
      - MYSQL_DATABASE=noria
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=noria
      - POSTGRES_DB=noria
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
