[package]
name = "channel"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
bincode = "0.8.0"
bufstream = "0.1.3"
byteorder = "1.0.0"
mio = "0.6.9"
serde = { version = "1.0.8", features = ["rc"] }
serde_derive = "1.0.8"
