# Default values for readyset.
# This is a YAML-formatted file.

# Disclaimer: Removing any of the following items from the list
# will likely break things in unspectacular ways.
readyset:
  # Deployment must be unique per consul cluster
  deployment:
  # query_caching_mode tells ReadySet how it should cache queries
  # Accepted values: explicit, async, in-request-path
  # Defaults to explicit mode
  query_caching_mode: explicit
  adapter:
    query_log_ad_hoc: true
    statement_logging: false
    ingress:
      enabled: true
    httpPort: 6034
    image:
      repository: # "public.ecr.aws/readyset" # No trailing slash
      tag: "latest"
    port: 3306 # Or 5432
    resources:
      requests:
        storage: "50Gi"
        cpu: "1000m"
        memory: "2Gi"
    type: "mysql" # Or 'postgresql'
  server:
    # replication_tables - comma separated list of schema, table pairs delimited by a '.'
    # To only replicate/snapshot all tables in the public schema, and only mytable in the myschema schema, you would pass
    # "public.*,myschema.mytable"
    # replication_tables: public.foo
    # statement_logging
    statement_logging: false
    httpPort: 6033
    resources:
      requests:
        # These values are the minimal for a successful deployment to GKE
        # TODO: provide guidance on how to calculate optimal values
        storage: "100Gi"
        cpu: "1000m"
        memory: "4Gi"
    image:
      repository: # "public.ecr.aws/readyset" # No trailing slash
      tag: "latest"

kubernetes:
  storageClass: # Leave empty to use default provisioner

# This configures the underlying consul service with 3 replicas
# See: https://developer.hashicorp.com/consul/docs/k8s/helm for more information
# on how to configure consul.
consul:
  enabled: true
  server:
    replicas: 3
    bootstrapExpect: 3
    resources:
      requests:
        memory: "1Gi"
        cpu: "1000m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
