# Default values for readyset.
# This is a YAML-formatted file.

# Disclaimer: Removing any of the following items from the list
# will likely break things in unspectacular ways.
readyset:
  database:
    type: mysql # or psql; Necessary to work with older versions of ReadySet
  adapter:
    ingress:
      enabled: true
    httpPort: 6034
    image:
      repository: # "public.ecr.aws/readyset" # No trailing slash
      tag: "latest"
    port: 3306 # Or 5432
    resources:
      requests:
        storage: "50Gi"
        cpu: 500m
        memory: "1Gi"
    type: "mysql" # Or 'postgresql'
  server:
    httpPort: 6033
    resources:
      requests:
        storage: "50Gi"
        cpu: 500m
        memory: "1Gi"
    image:
      repository: # "public.ecr.aws/readyset" # No trailing slash
      tag: "latest"


kubernetes:
  storageClass: # Leave empty to use default provisioner

# This configures the underlying consul service with 3 replicas
# See: https://developer.hashicorp.com/consul/docs/k8s/helm for more information
# on how to configure consul.
consul:
  enabled: true
  server:
    replicas: 3
    bootstrapExpect: 3
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
