[package]
name = "readyset-client-adapter"
publish = false
version = "0.1.0"
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
clap = { version = "3.0", features = ["derive","env"] }
futures-util = "0.3.0"
fail = "0.5.0"
failpoint-macros = { path = "../failpoint-macros" }
maplit = "1.0.2"
metrics = "0.19"
metrics-exporter-prometheus = "0.10"
tokio = { version = "1.15", features = ["signal", "rt-multi-thread", "time", "net"] }
tokio-stream = { version = "0.1.5", features = ["net"] }
tracing = { version = "0.1", features = ["release_max_level_debug"] }
tracing-subscriber = "0.3.9"
tracing-futures = "0.2.5"
stream-cancel = "0.8.0"
reqwest = { version = "0.11", features = ["json"] }
chrono = "0.4"

# Local dependencies
launchpad = { path = "../launchpad" }
nom-sql = { path = "../nom-sql" }
readyset = { path = "../readyset/" }
readyset-adapter = { path = "../readyset-adapter" }
readyset-client-metrics = { path = "../readyset-client-metrics" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-dataflow = { path = "../readyset-dataflow" }
readyset-data = { path = "../readyset-data" }
readyset-server = { path = "../readyset-server/" }
readyset-telemetry-reporter = { path = "../readyset-telemetry-reporter" }
readyset-sql-passes = { path = "../readyset-sql-passes" }
readyset-version = { path = "../readyset-version" }
health-reporter = { path = "../health-reporter" }

[features]
failure_injection = ["fail/failpoints"]
fallback_cache = ["readyset-adapter/fallback_cache", "readyset-client-metrics/fallback_cache"]
