[package]
name = "test-utils-proc-macros"
version = "0.0.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "1", default_features = false, features = ["full", "parsing", "printing", "proc-macro", "extra-traits", "clone-impls"] }
