[package]
name = "system-benchmarks"
version = "0.1.0"
edition = "2021"
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
publish = false

[dependencies]
anyhow = "1.0"
itertools = "0.10"
tokio = { version = "1.20", features = [ "macros" ] }
reqwest = { version = "0.11", features = [ "blocking" ] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
benchmarks = { path = "../benchmarks" }
database-utils = { path = "../database-utils" }
nom-sql = { path = "../nom-sql" }

readyset = { path = "../readyset" }
readyset-data = { path = "../readyset-data" }
readyset-mysql = { path = "../readyset-mysql" }
readyset-client-adapter = { path = "../readyset-client-adapter" }

clap = { version = "3.0", features = ["derive"] }
core_affinity = "0.5"
criterion = { version = "0.3", features = ["async_tokio"] }
fork = "0.1"
futures = "0.3"
num_cpus = "1.13"
mysql_async = "0.29"
parking_lot = "0.12"
temp-dir = "0.1"
tikv-jemallocator = "0.4"

regex = "1.5"

bincode = "1.3"

nperf-core = { git = "https://github.com/readysettech/not-perf.git" }
structopt = "0.2"
libc = "0.2"

[[bin]]
name = "regressions"
test = false
bench = false

[[bench]]
name = "workload"
harness = false

[features]
fallback_cache = ["readyset-client-adapter/fallback_cache", "readyset-mysql/fallback_cache"]
disk_modeled = ["fallback_cache", "readyset-client-adapter/fallback_cache", "readyset-mysql/fallback_cache"]
