[package]
name = "readyset-repl"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "3.0", features = ["derive", "wrap_help"] }
console = "0.15.0"
rustyline = "9.1"
rustyline-derive = "0.6.0"
tokio = { workspace = true, features = ["full"] }
prettytable-rs = "0.8.0"
textwrap = "0.14"
nom = "7.1.1"

database-utils = { path = "../database-utils" }
readyset-data = { path = "../readyset-data" }
readyset-errors = { path = "../readyset-errors" }
