[package]
name = "readyset-mir"
version = "0.7.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"
description = "ReadySet MIR crate"

[dependencies]
regex = "1.5"
lazy_static = "1.4"
petgraph = { version = "0.5", features = ["serde-1"] }
itertools = "0.10"
tracing = { version = "0.1", features = ["release_max_level_debug"] }
serde = { version = "1.0.8", features = ["rc", "derive"] }
proptest = "1.0.0"

# local deps
common = { path = "../readyset-common", package = "readyset-common" }
dataflow = { path = "../readyset-dataflow", package = "readyset-dataflow" }
nom-sql = { path = "../nom-sql" }
readyset-client = { path = "../readyset-client" }
readyset-errors = { path = "../readyset-errors" }
readyset-data = { path = "../readyset-data" }
fixedbitset = { version = "0.2.0", default-features = false }
readyset-tracing = { path = "../readyset-tracing" }

