[package]
name = "mir"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
regex = "0.2.2"
slog = "2.2.2"

# git deps
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "d8c96eae6fb0c5a9aba34fd49fcde459e0eea131" }

# local deps
core = { path = "../core" }
dataflow = { path = "../dataflow" }
