[package]
name = "mir"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
regex = "0.2.2"
slog = "2.2.2"

# git deps
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "de3d660a9e1faea07da506e1ea973d239d3606a1" }

# local deps
core = { path = "../core" }
dataflow = { path = "../dataflow" }
