[package]
name = "mir"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
regex = "0.2.2"
slog = "2.0.6"

# git deps
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "af113901265d5d9add36ac8f7ff1abee75a220be" }

# local deps
core = { path = "../core" }
dataflow = { path = "../dataflow" }
