[package]
name = "mir"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
regex = "0.2.2"
slog = "2.0.6"

# git deps
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "a7715d36c79ff3ee840a7f749c0e9234e1cf0ad2" }

# local deps
core = { path = "../core" }
dataflow = { path = "../dataflow" }
