[package]
name = "mir"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
regex = "0.2.2"
slog = "2.0.6"

# git deps
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "c7adeb210ccd282ee8c6df6603f2335b0bdcec3b" }

# local deps
core = { path = "../core" }
dataflow = { path = "../dataflow" }
