[package]
name = "mir"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
regex = "0.2.2"
slog = "2.0.6"

# git deps
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "41a2c94c6b3f5947588610c3766d8eaf7e11ab6d" }

# local deps
core = { path = "../core" }
dataflow = { path = "../dataflow" }
