[package]
name = "mir"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
regex = "0.2.2"
slog = "2.0.6"

# git deps
nom_sql = { git = "https://github.com/ms705/nom-sql.git", rev = "878e5d1bd05d2e7a33a6ceff311305b9dbdd6c09" }

# local deps
core = { path = "../core" }
dataflow = { path = "../dataflow" }
