[package]
name = "mir"
version = "0.1.0"
authors = ["The Distributary Developers"]

[dependencies]
regex = "0.2.2"
slog = "2.2.2"

# git deps
nom-sql = { git = "https://github.com/ms705/nom-sql.git", rev = "f363a641308aae4d3e9f1104fbc56911bd851395" }

# local deps
core = { path = "../core" }
dataflow = { path = "../dataflow" }
