---
apiVersion: v1
kind: ConfigMap
metadata:
  name: readyset-consul-agent-cm
  namespace: default
  labels: {{ include "readyset.labels" . | nindent 4 }}
data:
  entrypoint.sh: |
      #/bin/sh
      set -e
      CONSUL_SERVER_NAMESPACE="${CONSUL_SERVER_NAMESPACE:-consul}"
      exec /usr/local/bin/docker-entrypoint.sh consul agent \
        -advertise="${ADVERTISE_IP}" \
        -bind=0.0.0.0 \
        -client=0.0.0.0 \
        -node-meta=host-ip:${HOST_IP} \
        -node-meta=pod-name:${MY_POD_NAME} \
        -hcl='leave_on_terminate = true' \
        -hcl='ports { grpc = 8502 }' \
        -config-dir=/consul/config \
        -data-dir=/consul/data \
        -retry-join="provider=k8s namespace=${CONSUL_SERVER_NAMESPACE} label_selector=\"app=consul,component=server,release=readyset\"" \
        -node="${MY_POD_NAME}" \
        -serf-lan-port=8301
