---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readyset-adapter
subjects:
- kind: ServiceAccount
  name: readyset-adapter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readyset-adapter
