
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readyset-server
subjects:
- kind: ServiceAccount
  name: readyset-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readyset-server
