[package]
name = "readyset-sql-passes"
version = "0.0.1"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
itertools = "0.10"
tracing = { version = "0.1" }
serde = "1.0.8"
vec1 = "1.6.0"

# Local dependencies
nom-sql = { path = "../nom-sql" }
readyset-errors = { path = "../readyset-errors" }
readyset-data = { path = "../readyset-data" }
readyset-tracing = { path = "../readyset-tracing" }
dataflow-expression = { path = "../dataflow-expression" }
