[package]
name = "readyset-tracing"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive","env"] }
once_cell = "1.9.0"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
parking_lot = "0.12.0"
rand = "0.8.5"
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.35"
tracing-opentelemetry = "0.18.0"
opentelemetry-otlp = { version = "0.11.0" }
opentelemetry-semantic-conventions = "0.10"
tracing-subscriber = { version = "0.3.9", features = ["env-filter", "json"] }
lazy_static = "1.0"

[dev-dependencies]
anyhow = "1.0.53"
tokio = { workspace = true, features = ["full"] }
tracing-attributes = "0.1.20"
